{% set name = "find-kedro" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 2f722d5c3b1b4a11ef736c1932c8b07278a849a3e81e6343ccf0c9ef4654f28d

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python
  entry_points:
    - find-kedro = find_kedro.cli:cli

requirements:
  host:
    - python
    - pip
  run:
    - python
    - kedro
    - click
    - colorama
    - pygments

test:
  imports:
    - find_kedro
  commands:
    - find-kedro --help

about:
  home: https://github.com/WaylonWalker/find-kedro
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: https://github.com/WaylonWalker/find-kedro

  description: |
    find-kedro is a small library to enhance your kedro experience. It looks through your modules to find kedro pipelines,
    nodes, and iterables (lists, sets, tuples) of nodes. It then assembles them into a dictionary of pipelines, each module
    will create a separate pipeline, and __default__ being a combination of all pipelines. This format is compatible with
    the kedro _create_pipelines format.
  doc_url: https://find-kedro.waylonwalker.com/
  dev_url: https://github.com/WaylonWalker/find-kedro

extra:
  recipe-maintainers:
    - WaylonWalker
